version: '3.9'
services:
  app:
    build: 
      context: ./API
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./API:/API
      - /API/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm start
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
    expose:
      - "27017"
    volumes:
        - mongo-data:/data/db
        - ./mongo-data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "80:4200"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=80
    depends_on:
      - app
volumes:
    mongo-data: {}