name: Angular CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change directory
      run: cd frontend
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
